### ISSUE TITLE
using `insert_managements.rb`

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#342]
I am trying to use the insert_managements.rb script on the pecandev server

I created a clone of the ebi_production database. It has user bety and is called ebi_production_20150810, so you can open it usng

```sh
psql -U bety ebi_production_20150810
```

I also configured the `/usr/local/dl/config/database.yml` such that the development settings looks like this:

```yml
development:
  adapter: postgis
  encoding: utf8
  reconnect: false
  database: ebi_production_20100810
  pool: 5
  username: bety
  password: bety
```

However, when I run

```sh
cd /usr/local/dl
rake dbconf
./script/insert_managements.rb --login=dlebauer --output=fertN_managements.sql ~/fertN_managements.csv 
```

I get the error

> ./script/insert_managements.rb:285:in `<main>': uninitialized constant User (NameError)

Am I doing something wrong? I can login to the web interface with my username = dlebauer, and I have also tried this with `--login=carya`, `--login=bety`. But get the same error.

The files I want to upload are all of the csv files in a [public folder on Dropbox](https://www.dropbox.com/sh/w9vbw0vw8me86iz/AAAXdijeNw96KrQx4CNQST49a?dl=0), and are also in the [bety_manuscript github repo](https://github.com/ebimodeling/bety_manuscript/blob/master/update_mgmts/)
