### ISSUE TITLE
Doc tweaks

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/bety#710]
1: Step 10: Compile Rails assets:

The entry regarding a sub website URL has URI instead. Not sure if that is meant to be "i" but I suspect its supposed to be "L"?

2: curl https://raw.githubusercontent.com/PecanProject/pecan/develop/scripts/load.bety.sh > script/load.bety.sh

should be

https://raw.githubusercontent.com/PecanProject/bety/develop/script/load.bety.sh

**Comment by serbinsh** [comment]
Also hit this warning/error on Step 15
```
bash-4.4$ script/load.bety.sh -a postgres -c -d betydb -e -g -m 2 -o bety -r 0
Did not find a sync_url in database, please update database, or provide script with DUMPURL. 
```

**Comment by KristinaRiemer** [comment]
We've also had this issue come up a couple of times now. It seems like it's because the URL that is used is broken somehow: https://terraref.ncsa.illinois.edu/bety/dump/bety.tar.gz. 

Our current workaround is to add a working DUMPURL to the docker-compose.yml. So the Bety image part of that looks like this: 

```
  bety:
    image: pecan/bety:${BRANCH:-latest}
    ports:
      - 8000:8000
    networks:
      - bety
    environment:
      - INITIALIZE_URL=-w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz
      - REMOTE_SERVERS=6
      - UNICORN_WORKER_PROCESSES=1
      - SECRET_KEY_BASE=thisissomereallllllylongsecretkeyandshouldbelongerthanthis
      - DUMPURL=https://terraref.ncsa.illinois.edu/bety/dump/bety6/bety.tar.gz
    depends_on:
      - postgres
    restart: unless-stopped
```

I assume this isn't a good long-term solution and there's a better way to do this?
